name: Streamlit Keep Alive

on:
  schedule:
    - cron: '0 * * * *'  # runs every 1 hour
  workflow_dispatch:       # allows manual trigger anytime

jobs:
  wake-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run wake-up script
        run: python main.py
